Added first version of file
kasia251011/parking-os-backend pull request #2
Opened 2023-12-12 20:26 UTC by Ewangelina

2023-12-12 21:36 UTC, kasia251011 requested changes
Pierwsze co to należałoby usunąć redundancję endpointów. Najlepiej zostawić tylko to pogrupowanie wg danej "tabeli". Czyli "users", "vehicles", "tickets" itp. Dodatkowo można usunąć przedrostek '/admin' z każdego endpointu

2023-12-16 10:08 UTC, kasia251011 commented on config/endpoints.yaml
> +          description: Amount of money in PLN
To bym wrzuciłą w jeden obiekt
costOfMaintenance {
 electricity,
 cleaning,
 security
}

2023-12-16 10:11 UTC, kasia251011 commented on config/endpoints.yaml
> +          description: Longitude of the parking lots location
To bym wrzuciła w obiekt: 
````
location: {
 city,
 address,
 latitude,
 longitude
}
```

2023-12-16 10:11 UTC, kasia251011 reviewed
.

2023-12-16 10:51 UTC, kasia251011 approved these changes

2023-12-16 11:54 UTC, cpprian approved these changes

2023-12-16 14:03 UTC, cpprian commented on config/endpoints.yaml
> +      properties:
nie potrzebujemy tutaj id?

2023-12-17 12:01 UTC, cpprian commented on config/endpoints.yaml
> +        '200':
może 201 Status Created?

2023-12-17 21:25 UTC, kasia251011 commented on config/endpoints.yaml
> +      properties:
Podobnież numer rejestracyjny ma pełnić rolę Id

2023-12-18 00:21 UTC, merged