Added users tickets, balance and vehicles, login, registration and blocking user
kasia251011/parking-os-backend pull request #53
Opened 2024-01-05 04:55 UTC by Ewangelina

2024-01-05 09:09 UTC, kasia251011 requested changes

2024-01-05 09:09 UTC, kasia251011 commented on docs/endpoints.yaml
> +            type: string
lepiej będzie zamiast query parametrów użyć body - tak jak w odpowiedniku tego endpointa POST /tickets

2024-01-05 09:09 UTC, kasia251011 commented on docs/endpoints.yaml
> +                description: Amount of money in PLN
wrzuć to w obiekt

2024-01-05 09:09 UTC, kasia251011 commented on docs/endpoints.yaml
> +            format: float
To powinno byc w body, a nie jako query parametr

2024-01-05 09:09 UTC, kasia251011 commented on docs/endpoints.yaml
> +            description: Primary key
to wrzuć do body

2024-01-05 09:09 UTC, kasia251011 commented on docs/endpoints.yaml
> +          description: Successful operation
Ten ednpoint powinien zwracać token w obiekcie

2024-01-05 09:09 UTC, kasia251011 commented on docs/endpoints.yaml
> +        - users
może utwrzórz tag "auth" i tam wrzuć to plus endpoint do logowania?

2024-01-05 09:09 UTC, kasia251011 commented on docs/endpoints.yaml
> +            format: password
Wrzuć to do body

2024-01-05 09:09 UTC, kasia251011 commented on docs/endpoints.yaml
> +                type: string
endoint powinein zwrócić token w obiekcie

2024-01-11 08:56 UTC, kasia251011 approved these changes
wstępnie jest ok

2024-01-11 13:23 UTC, cpprian commented
czy w tabeli user nie powinniśmy przechowywać roli?

2024-01-11 14:17 UTC, cpprian approved these changes

2024-01-13 13:53 UTC, merged